name: Typescript Package CI

on: push

jobs:
  typescript:
    uses: skyleague/node-standards/.github/workflows/reusable-typescript.yml@next
    secrets:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: skyleague/node-standards/.github/workflows/reusable-build.yml@next
    secrets:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [typescript, build]
    uses: skyleague/node-standards/.github/workflows/reusable-release.yml@next
    with:
      build_artifact_name: ${{ needs.build.outputs.artifact_name }}
    secrets:
      GITHUB_NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
